name: artifacts workflow

on:[push]

env:
 ${{env.ARTIFACT_NAME}}
 path: .: test-artifact

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -name: checkout code
    uses: actions/checkout@v2
    -name: upload artifacts
    uses: actions/upload-artifact@v2
    with:
      name: ${{env.ARTIFACT_NAME}}
      path: .
    
