name: artifacts workflow

on: [push]

env:
 ARTIFACT_NAME: test-artifact

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -name: checkout code
    uses: actions/checkout@v2
    -name: uploadin artifacts
    uses: actions/upload-artifact@v2
    with:
      name: ${{env.ARTIFACT_NAME}}
      path: .
    
