name: artifacts workflow

on: [push]

env:
 ARTIFACT_NAME: test-artifact

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: checkout the code
      uses: actions/checkout@v2
    - name: upload the artifact
      uses: actions/upload-artifact@v2
      with:
       name: ${{env.test-artifact}}
       path: .

    
   
